
"""
ComfyUI GPT Image 2 插件
仅包含 GPT Image 2 相关节点
作者：AI剑歌
版本：1.0.0
"""

# 加载 GPT Image 2 节点
from .gpt_image_2_node import NODE_CLASS_MAPPINGS as GPT_IMAGE2_MAPPINGS
from .gpt_image_2_node import NODE_DISPLAY_NAME_MAPPINGS as GPT_IMAGE2_DISPLAY_MAPPINGS

# 加载 GPT Image 2 官方稳定节点
from .gpt_image_2_official_stable_node import NODE_CLASS_MAPPINGS as GPT_IMAGE2_OFFICIAL_STABLE_MAPPINGS
from .gpt_image_2_official_stable_node import NODE_DISPLAY_NAME_MAPPINGS as GPT_IMAGE2_OFFICIAL_STABLE_DISPLAY_MAPPINGS

# 加载 GPT Image 2 官方 4K 节点
from .gpt_image_2_official_4k_node import NODE_CLASS_MAPPINGS as GPT_IMAGE2_OFFICIAL_4K_MAPPINGS
from .gpt_image_2_official_4k_node import NODE_DISPLAY_NAME_MAPPINGS as GPT_IMAGE2_OFFICIAL_4K_DISPLAY_MAPPINGS

# 加载 GPT Image 2 综合节点
from .gpt_image_2_comprehensive_node import NODE_CLASS_MAPPINGS as GPT_IMAGE2_COMPREHENSIVE_MAPPINGS
from .gpt_image_2_comprehensive_node import NODE_DISPLAY_NAME_MAPPINGS as GPT_IMAGE2_COMPREHENSIVE_DISPLAY_MAPPINGS

# 加载 GPT 智能对话节点
from .gpt_smart_chat_node import NODE_CLASS_MAPPINGS as GPT_SMART_CHAT_MAPPINGS
from .gpt_smart_chat_node import NODE_DISPLAY_NAME_MAPPINGS as GPT_SMART_CHAT_DISPLAY_MAPPINGS

# 加载翻译和优化节点
from .jg_translation_node import NODE_CLASS_MAPPINGS as JG_TRANSLATION_MAPPINGS
from .jg_translation_node import NODE_DISPLAY_NAME_MAPPINGS as JG_TRANSLATION_DISPLAY_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **GPT_IMAGE2_MAPPINGS,
    **GPT_IMAGE2_OFFICIAL_STABLE_MAPPINGS,
    **GPT_IMAGE2_OFFICIAL_4K_MAPPINGS,
    **GPT_IMAGE2_COMPREHENSIVE_MAPPINGS,
    **GPT_SMART_CHAT_MAPPINGS,
    **JG_TRANSLATION_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **GPT_IMAGE2_DISPLAY_MAPPINGS,
    **GPT_IMAGE2_OFFICIAL_STABLE_DISPLAY_MAPPINGS,
    **GPT_IMAGE2_OFFICIAL_4K_DISPLAY_MAPPINGS,
    **GPT_IMAGE2_COMPREHENSIVE_DISPLAY_MAPPINGS,
    **GPT_SMART_CHAT_DISPLAY_MAPPINGS,
    **JG_TRANSLATION_DISPLAY_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]

__version__ = "1.0.0"
__author__ = "AI剑歌"
